export const GET_VIDEOJUEGOS = "GET_VIDEOJUEGOS";
export const GET_BY_DETALLE = "GET_BY_DETALLE";
export const GET_BY_NOMBRE = "GET_BY_NOMBRE";
export const GET_GENEROS = "GET_GENEROS";
export const GET_PLATAFORM = "GET_PLATAFORM";
export const FILTER_GENEROS = "FILTER_GENEROS";
export const ORDER_NOMBRE = "ORDER_NOMBRE";
export const ORDER_RATING = "ORDER_RATING";
export const GET_CREADOS = "GET_CREADOS";
export const CREATE_JUEGO = "CREATE_JUEGO";


